### PR TITLE
Make the training/webinar banner trilingual

### PR DESCRIPTION
**Pull request by tlxo**
This PR will duplicate the training banner and the underlying logic to show a relevant banner to visitors with browsers in English and Swedish.

### CODE REVIEW

**Comment by elguitar** [comment]
Approved PRs are not supposed to be left hanging. Please merge :slightly_smiling_face:

**Comment by tlxo** [comment]
Actually, I think we might want to change the links before merging. 

I was thinking that we might want to use https://seravo.com/tag/webinar/ (and equivalent for the sites in Finnish and Swedish). That way the link on the banner will always be relevant, regardless of whether we have new webinars on the horizon or not. (The blog posts are always gonna include YouTube embeds of the past webinars.)

**Comment by ottok** [comment]
@tlxo Did you check how this looks like now after merging?

image

**Comment by tlxo** [comment]
I'll investigate.

**Comment by tlxo** [comment]
This is how it looks (and looked) like to me on Safari.  Chrome works as well but Firefox seems to be doing something interesting.

Screenshot 2020-06-01 17 45 50

**Comment by elguitar** [comment]
Fixed via https://github.com/Seravo/docs/commit/ecb464f6e3cd023fad1ccf43cfd86fd62327520d Screenshot_20200603_094234

**Pull request merged**
